//【スキン情報】

;スキンの名前。タイトル画面に表示される。
Name=AquaStyle Red

;lスキンのバージョン。タイトル画面に表示される。
Version=1

;スキンの製作者名、タイトル画面に表示される。
Creator=Aquachan


//【タイトル画面】


//【設定画面】


//【選曲画面】

;選曲画面の基準座標
SongSelect_Overall_Y=103

;ネームプレートのX座標。(1P,2P)
SongSelect_NamePlate_X=49,945

;ネームプレートのY座標。(1P,2P)
SongSelect_NamePlate_Y=640,640

;オートマークのX座標。(1P,2P)
SongSelect_Auto_X=49,945

;オートマークのY座標。(1P,2P)
SongSelect_Auto_Y=640,640

;J-POPジャンルの曲表示の文字色。(16進数カラーコード)
SongSelect_FontColor_JPOP=#FFFFFF

;アニメジャンルの曲表示の文字色。(16進数カラーコード)
SongSelect_FontColor_Anime=#FFFFFF

;VOCALOIDジャンルの曲表示の文字色。(16進数カラーコード)
SongSelect_FontColor_VOCALOID=#FFFFFF

;どうようジャンルの曲表示の文字色。(16進数カラーコード)
SongSelect_FontColor_Children=#FFFFFF

;バラエティジャンルの曲表示の文字色。(16進数カラーコード)
SongSelect_FontColor_Variety=#FFFFFF

;クラシックジャンルの曲表示の文字色。(16進数カラーコード)
SongSelect_FontColor_Classic=#FFFFFF

;ゲームジャンルの曲表示の文字色。(16進数カラーコード)
SongSelect_FontColor_GameMusic=#FFFFFF

;ナムコジャンルの曲表示の文字色。(16進数カラーコード)
SongSelect_FontColor_Namco=#FFFFFF

;J-POPジャンルの曲表示の背景色。(16進数カラーコード)
SongSelect_BackColor_JPOP=#01455B

;アニメジャンルの曲表示の背景色。(16進数カラーコード)
SongSelect_BackColor_Anime=#9D3800

;VOCALOIDジャンルの曲表示の背景色。(16進数カラーコード)
SongSelect_BackColor_VOCALOID=#5B6278

;どうようジャンルの曲表示の背景色。(16進数カラーコード)
SongSelect_BackColor_Children=#99001F

;バラエティジャンルの曲表示の背景色。(16進数カラーコード)
SongSelect_BackColor_Variety=#366600

;クラシックジャンルの曲表示の背景色。(16進数カラーコード)
SongSelect_BackColor_Classic=#875600

;ゲームジャンルの曲表示の背景色。(16進数カラーコード)
SongSelect_BackColor_GameMusic=#412080

;ナムコジャンルの曲表示の背景色。(16進数カラーコード)
SongSelect_BackColor_Namco=#980E00


//【演奏画面】

;選曲画面の基準座標
SongSelect_Overall_Y=103

;音符のアニメーションを使用するかどうか。
Game_Notes_Anime=1

;曲数テキストの文字。
StageText=1曲目

;曲数テキストの文字の縁取りを赤色にするかどうか。
IsStageTextRed=0

;キャラのX座標。(1P,2P)
Game_Chara_X=0,0

;キャラのY座標。(1P,2P)
Game_Chara_Y=0,537

;キャラの通常時モーション指定。(カンマ区切り)
Game_Chara_Motion_Normal=0,0,0,0,1,2,3,4,5,6,6,5,4,3,2,1,0,0,0,0,1,2,3,4,5,6,6,5,4,3,2,1,0,0,0,0,1,2,3,4,5,6,6,5,7,8,9,10,11,11,11,11,10,9,8,7,13,12,12,13,14,15,16,17

;キャラのクリア時モーション指定。(カンマ区切り)
Game_Chara_Motion_Clear=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29

;キャラのゴーゴータイム時モーション指定。(４分の4拍子換算)
Game_Chara_Motion_GoGo=42,43,43,44,45,46,47,48,49,50,51,52,53,54,55,0,1,2,3,4,5,6,7,8,9,11,12,13,14,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41

;キャラの通常時モーションが何拍子でループするか。(カンマ区切り)
Game_Chara_Beat_Normal=4

;キャラのクリア時モーションが何拍子でループするか。(カンマ区切り)
Game_Chara_Beat_Clear=2

;キャラのゴーゴータイム時モーションが何拍子でループするか。(カンマ区切り)
Game_Chara_Beat_GoGo=4

ふうせん連打時のキャラ画像X座標。(1P,2P)
Game_Chara_Ballon_X=240

ふうせん連打時のキャラ画像X座標。(1P,2P)
Game_Chara_Ballon_Y=240

;ダンサーのX座標。(登場順)
Game_Dancer_X=640,430,856,215,1070

;ダンサーのY座標。(登場順)
Game_Dancer_Y=580,580,580,580,580

;ダンサーのモーション指定。(カンマ区切り)
Game_Dancer_Motion=0,0,0,0,0,0,0,0,0,0,1,2,3,4,5,0,1,2,3,4,5,0,1,2,3,4,5,0,1,2,3,4,5,0,1,2,3,4,5,0,1,2,3,4,5,0,1,2,3,4,5,0,1,2,3,4,5,0,6,7,7,7,7,7,7,7,7,7,7,8,9,10,11,12,12,12,12,12,12,12,12,12,12,10,9,8,6,7,7,7,7,7,7,7,7,7,7,8,9,10,11,12,12,12,12,12,12,12,12,12,12,10,9,8

;ダンサーのモーションが何拍子でループするか。(4分の4拍子換算)
Game_Dancer_Beat=16

;ダンサーの出現タイミング。(魂ゲージn%)
Game_Dancer?Gauge=0,20,40,60,80

;Mobのモーションが何拍子でループするか。(4分の4拍子換算)
Game_Mob_Beat=1

;Mobのパターンが何拍子でループするか。(4分の4拍子換算)
Game_Mob_Ptn_Beat=1

;コースシンボルのX座標。(1P,2P)
Game_CourseSymbol_X=7,7

;コースシンボルのY座標。(1P,2P)
Game_CourseSymbol_Y=232,370

;ネームプレートの座標。(1P,2P)
Game_Taiko_NamePlate_X=322,322

;ネームプレートの座標。(1P,2P)
Game_Taiko_NamePlate_Y=22,636

;プレイヤーナンバーのX座標。(1P,2P)
Game_Taiko_PlayerNumber_X=9999,9999

;プレイヤーナンバーのY座標。(1P,2P)
Game_Taiko_PlayerNumber_Y=9999,9999

;虹ゲージタイマーの更新間隔
Game_Gauge_Rainbow_Timer=83

;ミニ太鼓のX座標。(1P,2P)
Game_Taiko_X=180,180

;ミニ太鼓のY座標。(1P,2P)
Game_Taiko_Y=190,366

;三桁未満コンボ数字のX座標。(1P,2P)(中央基準)
Game_Taiko_Combo_X=251,251

;三桁未満コンボ数字のY座標。(1P,2P)(下基準)
Game_Taiko_Combo_Y=265,443

;三桁以上コンボ数字のX座標。(1P,2P)(中央基準)
Game_Taiko_Combo_Ex_X=250,250

;三桁以上コンボ数字のY座標。(1P,2P)(下基準)
Game_Taiko_Combo_Ex_Y=269,447

;四桁以上コンボ数字のX座標。(1P,2P)(中央基準)
Game_Taiko_Combo_Ex4_X=250,250

;四桁以上コンボ数字のY座標。(1P,2P)(下基準)
Game_Taiko_Combo_Ex4_Y=269,447

;コンボ表示のリピート幅(2桁,3桁,4桁以上)
Game_Taiko_Combo_Padding=42,43,38

;三桁未満コンボ数字の大きさ。(Width,Height)
Game_Taiko_Combo_Size=44,51

;三桁以上コンボ数字の大きさ。(Width,Height)
Game_Taiko_Combo_Size_Ex=50,65

;コンボ表示の拡大率。(3桁未満,3桁,4桁以上)
Game_Taiko_Combo_Scale=1.0,1.0,0.88

コンボ文字のX座標。(1P,2P)(中央基準)
Game_Taiko_Combo_Text_X=250,250

コンボ文字のY座標。(1P,2P)(下基準)
Game_Taiko_Combo_Text_Y=300,478

;三桁未満コンボ文字の大きさ。(Width,Height)
Game_Taiko_Combo_Text_Size=100,50

;三桁以上コンボ文字の大きさ。(Width,Height)
Game_Taiko_Combo_Text_Size_Ex=100,50

;スコア表示X座標。(1P,2P)(中央基準)
Game_Score_X=20,20

;スコア表示Y座標。(1P,2P)(下基準)
Game_Score_Y=224,529

スコア加算のX座標。(1P,2P)(中央基準)
Game_ScoreAdd_X=25,25

スコア加算のY座標。(1P,2P)(下基準)
Game_ScoreAdd_Y=184,569

;コンボボーナス加算のX座標。(1P,2P)(中央基準)
Game_ScoreAddBonus_X=25,25

;コンボボーナス加算のY座標。(1P,2P)(下基準)
Game_ScoreAddBonus_Y=134,619

;スコア表示のリピート幅。(px)
Game_Score_Padding=20

;スコア文字の大きさ。(Width,Height)
Game_Score_Size=24,33

;コンボボーナス時の枠X座標。(1P,2P)
Game_Balloon_Combo_X=253,253

;コンボボーナス時の枠Y座標。(1P,2P)
Game_Balloon_Combo_Y=-11,548

;コンボボーナス時の数字X座標。(1P,2P)
Game_Balloon_Combo_Number_X=312,312

;コンボボーナス時の数字Y座標。(1P,2P)
Game_Balloon_Combo_Number_Y=34,590

;コンボボーナス時(1000コンボ以上)の数字X座標。(1P,2P)
Game_Balloon_Combo_Number_Ex_X=335,335

;コンボボーナス時(1000コンボ以上)の数字Y座標。(1P,2P)
Game_Balloon_Combo_Number_Ex_Y=34,590

;コンボボーナス時の文字X座標。(1P,2P)
Game_Balloon_Combo_Text_X=473,473

;コンボボーナス時の文字Y座標。(1P,2P)
Game_Balloon_Combo_Text_Y=55,611

;コンボボーナス時(1000コンボ以上)の文字X座標。(1P,2P)
Game_Balloon_Combo_Text_Ex_X=498,498

;コンボボーナス時(1000コンボ以上)の文字Y座標。(1P,2P)
Game_Balloon_Combo_Text_Ex_Y=55,611

;ふうせん連打時のふうせんX座標。(1P,2P)
Game_Balloon_Balloon_X=398,398

;ふうせん連打時のふうせんY座標。(1P,2P)
Game_Balloon_Balloon_Y=115,412

;ふうせん連打時の枠X座標。(1P,2P)
Game_Balloon_Balloon_Frame_X=393,393

;ふうせん連打時の枠Y座標。(1P,2P)
Game_Balloon_Balloon_Frame_Y=31,329

;ふうせん連打時の数字X座標。(1P,2P)
Game_Balloon_Balloon_Number_X=497,497

;ふうせん連打時の数字Y座標。(1P,2P)
Game_Balloon_Balloon_Number_Y=140,438

;連打時の枠X座標。(1P,2P)
Game_Balloon_Roll_Frame_X=218,218

;連打時の枠Y座標。(1P,2P)
Game_Balloon_Roll_Frame_Y=-3,514

;連打時の数字X座標。(1P,2P)
Game_Balloon_Roll_Number_X=392,392

;連打時の数字X座標。(1P,2P) (下基準)
Game_Balloon_Roll_Number_Y=128,639

;ふうせん連打、連打の数字の大きさ。(Width, Height)
Game_Balloon_Number_Size=62,80

;ふうせん連打、連打の数字のリピート幅。(px)
Game_Balloon_Number_Padding=60

;連打時の数字の拡大率。
Game_Balloon_Roll_Number_Scale=1.000

;ふうせん連打の数字の拡大率。
Game_Balloon_Balloon_Number_Scale=0.879

;ランナー画像の一コマのサイズ (X,Y)
Game_Runner_Size=125,170

;ランナー画像のパターン枚数
Game_Runner_Ptn=44

;ランナー画像の出てくるバリエーション (ミス時省く)
Game_Runner_Type=4

;ランナー画像の出てくる座標 (1P,2P)
Game_Runner_StartPoint_X=170,175
Game_Runner_StartPoint_Y=20,500

;ランナーに使用するタイマーの更新間隔 (ms)
Game_Runner_Timer=10


//【リザルト画面】

;ネームプレートのX座標。(1P,2P)
Result_NamePlate_X=238,9999

;ネームプレートのY座標。(1P,2P)
Result_NamePlate_Y=98,9999


//【終了画面】


